### ISSUE TITLE
NewRelicClient does not follow redirects

### ISSUE THREAD

**Issue by twerszko** [ocadotechnology/newrelic-alerts-configurator#58]
Apparently NewRelic returns http link instead of https one in pageable responses and the client does not follow redirects:
```
[main] INFO com.ocadotechnology.newrelic.apiclient.internal.client.NewRelicClientInterceptor - GET https://api.newrelic.com/v2/alerts_channels.json: 200 OK
[main] INFO com.ocadotechnology.newrelic.apiclient.internal.client.NewRelicClientInterceptor - GET http://api.newrelic.com/v2/alerts_channels.json?page=2
[main] INFO com.ocadotechnology.newrelic.apiclient.internal.client.NewRelicClientInterceptor - GET http://api.newrelic.com/v2/alerts_channels.json?page=2: 302 Moved Temporarily
[main] INFO com.ocadotechnology.newrelic.apiclient.internal.client.NewRelicClientInterceptor - 
Exception in thread "main" com.ocadotechnology.newrelic.apiclient.internal.client.NewRelicClientException: GET http://api.newrelic.com/v2/alerts_channels.json?page=2: 302 Moved Temporarily
	at com.ocadotechnology.newrelic.apiclient.internal.client.NewRelicClientInterceptor.filter(NewRelicClientInterceptor.java:35)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:257)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
	at com.ocadotechnology.newrelic.apiclient.internal.ApiBase.followPageable(ApiBase.java:29)
	at com.ocadotechnology.newrelic.apiclient.internal.ApiBase.getPageable(ApiBase.java:24)
	at com.ocadotechnology.newrelic.apiclient.internal.DefaultAlertsChannelsApi.list(DefaultAlertsChannelsApi.java:26)
	at com.ocadotechnology.newrelic.alertsconfigurator.ChannelConfigurator.createOrUpdatePolicyAlertsChannels(ChannelConfigurator.java:44)
	at com.ocadotechnology.newrelic.alertsconfigurator.ChannelConfigurator.sync(ChannelConfigurator.java:37)
	at com.ocadotechnology.newrelic.alertsconfigurator.Configurator.sync(Configurator.java:[87](https://gitlab.ocado.tech/gm-lms/tools/newrelic-alerts-configuration/-/jobs/135077953#L87))
	at com.ocado.gm.ordermanagement.NewRelicConfiguratorKt.main(newRelicConfigurator.kt:38)
```

**Comment by twerszko** [comment]
Looks like the default connector factory does not work as expected. It works well with `ApacheConnectorFactory` (https://stackoverflow.com/a/42207776).
Pull request created https://github.com/ocadotechnology/newrelic-alerts-configurator/pull/59

**Comment by twerszko** [comment]
Here is a version with refactoring that should allow users to provide custom NewRelicClient.
https://github.com/ocadotechnology/newrelic-alerts-configurator/pull/60
